name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:13
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Upload venv artifact
        run: tar -czf venv.tar.gz .venv

      - uses: actions/upload-artifact@v4
        with:
          name: venv
          path: venv.tar.gz

  lint:
    runs-on: ubuntu-latest
    container: debian:13
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download venv artifact
        uses: actions/download-artifact@v4
        with:
          name: venv

      - name: Extract venv
        run: tar -xzf venv.tar.gz

      - name: Run ruff
        shell: bash
        run: .venv/bin/ruff check .

  tests:
    runs-on: ubuntu-latest
    container: debian:13
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download venv artifact
        uses: actions/download-artifact@v4
        with:
          name: venv

      - name: Extract venv
        run: tar -xzf venv.tar.gz

      - name: Run pytest
        shell: bash
        run: xvfb-run -a .venv/bin/pytest --cov=cdisplayagain --cov-report=xml --cov-fail-under=75

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
