name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: debian:13
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run ruff
        shell: bash
        run: uv run ruff check .

  tests:
    runs-on: ubuntu-latest
    container: debian:13
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run pytest
        shell: bash
        run: xvfb-run -a uv run pytest --cov=cdisplayagain --cov-report=xml --cov-fail-under=75

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
